clean:
	rm -f *.dat NSH* SH* Z bkup-* compare.txt RNDB.txt.LCK seed.txt DB.txt
	rm -Rf nshtmp*
	rm -Rf cshtmp*
	rm -Rf SAT

realclean:
	rm -f *.dat NSH* SH* Z bkup-* compare.txt RNDB.txt.LCK seed.txt DB.txt
	rm -Rf nshtmp*
	rm -Rf SAT
	rm -f *.pl~
	rm -f *.po
	rm -f *.itf	
