% Produces a list of numbers generated by a decreasing fator N, so that 
% Xi = Xi-1 - N, Xi+1 = Xi - N - 1.

:- use_module(clpfd_rt).
:- use_module(clpfd_idx).
:- use_module(library(prolog_sys), [statistics/2]).
:- use_module(library(format)).

dec_seqs(N, L) :-
	statistics(runtime,_),
	do_seqs(N,_,L),
	labeling([ff], L), 
	statistics(runtime,[_, Time]),
	format("Used ~d milliseconds~n", Time).


do_seqs(N, A, [A|L]) :-
	'a<b'(0,N),
	'a+b=c'(B,N,A),
	'a+t=c'(N, -1, N1),
	do_seqs(N1, B, L),
	all_different([A|L]).
do_seqs(0,0,[]).
