* DONE Port new attributed variables (SWI)
  CLOSED: [2011-05-31 Mar 14:36]

  We will port the version described in:
    http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.142.3985
  (that is implemented in SWI prolog:
    http://www.swi-prolog.org/pldoc/doc_for?object=section(2,'6.1',swi('/doc/Manual/attvar.html'))
  )

  The SICStus version is described in:
    http://www.sics.se/sicstus/docs/latest4/html/sicstus.html/lib_002datts.html#lib_002datts

* Compatibility package/module 'atts'
** DONE Implemented in Prolog mimicking low-level behaviour
   CLOSED: [2011-05-31 Mar 14:36]
** Previous Ciao implementation attempts
   ciao/library/swi_mattr_global
   (uses ciao/library/mattr_global)

   Those are not used (move to contrib, deprecate, etc.):

     ciao/library/mattr_local
     ciao/library/mattr_sicstus
** Move to low-level code (engine) -- With a C FLAG

* DONE Adapt CLP(fd) (Emilio)
  CLOSED: [2012-02-20 Mon 11:46]
  ciao/contrib/clpfd/
* Port from SWI
** Global variables (nonbacktrackable)
   They are required by CLP(R,Q)

   Their implementation is not trivial. Nonbacktrackable globals are
   based on a freeze-bar for the global heap, that affects GC.
** New CHR
** New CLP(R,Q)
* Adapt old CLP(R,Q) and/or port new CLP(R,Q)
  It is *impossible* to adapt the old code to the new one. The new
  attributes force unification.

  See this code:
#+begin_example
?- {X >= 10.0, X =< 10.0}, X = 10.0.
X = 10.0.

?- {X >= 10.0, X =< 10.0}, {X = 10.0}.
X = 10.0.

?- 
|    .
ERROR: Stream user_input:5:29 Syntax error: Unexpected end of clause
?- {X >= 10.0, X =< 10.0}, {X = 10}.
X = 10.0.

?- 
|    {X >= 10.0, X =< 10.0}, X = 10.
false.
#+end_example

* Adapt other code

  grep -nH -r -e 'update_attributes' . --include='*.pl'
  grep -nH -r -e 'verify_attributes' . --include='*.pl'

* Problem: linear complexity of update_attribute
  Hint: it is not possible to remove attributes in the new model.

** optimized undo goal setarg-like for CVA?
   MC said that maybe there is a free tag.
   (We can implement it even if there is no free tag)

* Problem: Pablo and attach_attribute on non-'unsafe' SVA 


