sat(var(true)).
sat(e(X,Y)) <- sat(X), sat(Y).
sat(ou(X,_)) <- sat(X).
sat(ou(_,X)) <- sat(X).
sat(n(X)) <- not sat(X).


/*

No Art of Prolog está assim:

sat(1).
sat(F) <- nonvar(F), F = e(X,Y), sat(X), sat(Y).
sat(F) <- nonvar(F), F = ou(X,Y), sat(X).
sat(F) <- nonvar(F), F = ou(X,Y), sat(Y).
sat(F) <- nonvar(F), F = n(X), inv(X).

inv(0).
inv(F) <- nonvar(F), F = ou(X,Y), inv(X), inv(Y).
inv(F) <- nonvar(F), F = e(X,Y), inv(X).
inv(F) <- nonvar(F), F = e(X,Y), inv(Y).
inv(F) <- nonvar(F), F = n(X), sat(X).

*/