void writechar(int ch, int i, stream_node_t *s);
bool_t flush_output(Argdecl);
bool_t flush_output1(Argdecl);
bool_t getct(Argdecl);
bool_t getct1(Argdecl);
bool_t get(Argdecl);
bool_t get2(Argdecl);
bool_t get1(Argdecl);
bool_t get12(Argdecl);
bool_t nl(Argdecl);
bool_t nl1(Argdecl);
bool_t put(Argdecl);
bool_t put2(Argdecl);
bool_t tab(Argdecl);
bool_t tab2(Argdecl);
bool_t skip(Argdecl);
bool_t skip2(Argdecl);
bool_t skip_line(Argdecl);
bool_t skip_line1(Argdecl);
void print_string(CIAO_REGISTER stream_node_t *stream, CIAO_REGISTER char *p);
void print_variable(Argdecl, stream_node_t *stream, tagged_t term);
void print_number(Argdecl, stream_node_t *stream, tagged_t term);
void print_atom(Argdecl, stream_node_t *stream, tagged_t term);
bool_t prolog_display(Argdecl);
bool_t prolog_display2(Argdecl);
bool_t prolog_displayq(Argdecl);
bool_t prolog_displayq2(Argdecl);
bool_t prolog_clearerr(Argdecl);
bool_t prolog_fast_read_in_c(Argdecl);
bool_t prolog_fast_write_in_c(Argdecl);
