clean: 
	/bin/rm -f *.o *.so *_glue.? *.asr *.ast *.itf *.po *~
	/bin/rm -f examples/bench/*.asr examples/bench/*.itf examples/bench/*.po examples/bench/*~
	/bin/rm -f examples/*.asr examples/*.itf examples/*.po examples/*~
	/bin/rm -f Tests/bench/*.asr Tests/bench/*.itf Tests/bench/*.po Tests/bench/*~
	/bin/rm -f Tests/*.asr Tests/*.itf Tests/*.po Tests/*~
	/bin/rm -f CCAT/*.o CCAT/*.so CCAT/*_glue.? CCAT/*.asr CCAT/*.ast CCAT/*.itf CCAT/*.po CCAT/*~
	/bin/rm -f ../difference_constraints/*.o ../difference_constraints/*.so ../difference_constraints/*_glue.? ../difference_constraints/*.asr ../difference_constraints/*.ast 
	/bin/rm -f ../difference_constraints/*.itf ../difference_constraints/*.po ../difference_constraints/*~
	/bin/rm -f ../difference_constraints/difference_constraints_tab/*.o ../difference_constraints/difference_constraints_tab/*.so ../difference_constraints/difference_constraints_tab/*_glue.? 
	/bin/rm -f ../difference_constraints/difference_constraints_tab/*.asr ../difference_constraints/difference_constraints_tab/*.ast 
	/bin/rm -f ../difference_constraints/difference_constraints_tab/*.itf ../difference_constraints/difference_constraints_tab/*.po ../difference_constraints/difference_constraints_tab/*~
	/bin/rm -f ../difference_constraints/difference_constraints_tab/examples/*.o ../difference_constraints/difference_constraints_tab/examples/*.so
	/bin/rm -f ../difference_constraints/difference_constraints_tab/examples/*.asr ../difference_constraints/difference_constraints_tab/examples/*.ast 
	/bin/rm -f ../difference_constraints/difference_constraints_tab/examples/*.itf ../difference_constraints/difference_constraints_tab/examples/*.po ../difference_constraints/difference_constraints_tab/examples/*~
	/bin/rm -f ../disequalities/*.o ../disequalities/*.so ../disequalities/*_glue.? ../disequalities/*.asr ../disequalities/*.ast 
	/bin/rm -f ../disequalities/*.itf ../disequalities/*.po ../disequalities/*~
	/bin/rm -f ../disequalities/disequalities_tab/*.o ../disequalities/disequalities_tab/*.so ../disequalities/disequalities_tab/*_glue.? 
	/bin/rm -f ../disequalities/disequalities_tab/*.asr ../disequalities/disequalities_tab/*.ast 
	/bin/rm -f ../disequalities/disequalities_tab/*.itf ../disequalities/disequalities_tab/*.po ../disequalities/disequalities_tab/*~
	/bin/rm -f ../disequalities/disequalities_tab/examples/*.o ../disequalities/disequalities_tab/examples/*.so
	/bin/rm -f ../disequalities/disequalities_tab/examples/*.asr ../disequalities/disequalities_tab/examples/*.ast 
	/bin/rm -f ../disequalities/disequalities_tab/examples/*.itf ../disequalities/disequalities_tab/examples/*.po ../disequalities/disequalities_tab/examples/*~
