clean:
	rm -f  RNDB.txt.LCK NSH* SH* seed.txt DB.txt
	rm -Rf nshtmp*
	rm -Rf cshtmp*
#	rm -Rf SAT

realclean:
#	rm -f *.dat NSH* SH* Z bkup-* compare.txt RNDB.txt.LCK
	rm -Rf nshtmp* 
	rm -Rf cshtmp*
#	rm -Rf SAT
	rm -f *~ NSH* SH* seed.txt DB.txt
	rm -f *.po 
	rm -f *.itf	
	rm -f *.aux
	rm -f *.dvi
	rm -f *.log
