clean: 
	/bin/rm -f *.o *.so *_glue.? *.asr *.ast *.itf *.po *~
	/bin/rm -f apll_nd/*.o apll_nd/*.so apll_nd/*_glue.? apll_nd/*.asr apll_nd/*.ast apll_nd/*.itf apll_nd/*.po apll_nd/*~
	/bin/rm -f examples/*.o examples/*.so examples/*_glue.? examples/*.asr examples/*.ast examples/*.itf examples/*.po examples/*~
	/bin/rm -f examples/TPLP/*.o examples/TPLP/*.so examples/TPLP/*_glue.? examples/TPLP/*.asr examples/TPLP/*.ast examples/TPLP/*.itf examples/TPLP/*.po examples/TPLP/*~