#!/bin/sh

# Replaces string $1 with string $2 in file $3 
# Leaves result in file $4

# Override shell clobbering
/bin/rm -f $4
# Use ':' instead of '/' to separate options
sed -e s:$1:$2:g < $3 > $4
