all:
	@echo "Only implemented clean."
clean:
	@echo "Cleaning tmp files ..."
	@# Tmp files
	rm -fRv *.bbl *.bbg *.blg *.aux *.toc *.out *.brf *.lof *.nav *.snm *.vrb
	rm -fRv *.lol *.lot *.log *.backup *.tex~ *.bib~ *.tex.* comment.cut 
	rm -fRv *.itf *.po *.pl.* *_co.pl *.idx 
	@# Produced files
	rm -fRv $(PAPER) $(PRESENTATION)
	@echo " "

