# ----------------------------------------------------------------------------
include ../SETTINGS
include ../COMMON
#-----------------------------------------------------------------------------

# Should install examples in library?
install:
	@echo "Nothing to be done"

uninstall: install

clean:
	@echo "*** ---------------------------------------------------------"
	@echo "*** Cleaning up $(BASEMAIN) examples directory..."
	@echo "*** ---------------------------------------------------------"
	-rm -f *.itf *.asr *.po *~ 

distclean: clean
# END
#-----------------------------------------------------------------------------
