:- module(dec_seqs, 
	[
	    do/0
	]).

% Produces a list of numbers generated by a decreasing fator N, so that 
% Xi = Xi-1 - N, Xi+1 = Xi - N - 1.

:- use_package(fd).

do :- 
	N = 100,
	M is N*N,
	A in 0 .. M,
	do_seqs(N,A,M,_).

do_seqs(N, A, M, [A|L]) :-
	N .>. 0,
	B in 0 .. M,
	A .=. B + N,
	N1 is N - 1,
	do_seqs(N1, B, M, L),
	all_different([A|L]).
do_seqs(0,0,_,[]).
