%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This program was generated by the preprocessor for           %
% Constructive Intensional Negation on Well Founded Semantics. %
%                                                              %
% Victor Pablos Ceruelo ( vpablos at babel.ls.fi.upm.es )      %
%                                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% The original program file name is: filmsDB.pl, and it contained: 
% -------------------------
% 
% (:-(module(filmsDB, _641, [rfuzzy,clpr]))).
% (film(The Godfather, 1972, 207, drama, english)).

 [sent: arg1]: film(The Godfather,1972,207,drama,english)
 [sent: arg1]: :-module(filmsDB,_641,[rfuzzy,clpr