#!/bin/sh
exec ../ciao-shell $0 "$@"

:- use_package([]).

:- use_module(library(system)).

main(Args) :-
    current_executable(E), display(E), display_args(Args), nl.

display_args([]).
display_args([A|As]) :-
    put_code(0' ), display(A),
    display_args(As).
    
