#include <stdio.h>

typedef struct bench {
  char *name;
  int all_bytecode;
  int program_bytecode;
  int eng_big;
  int loop_big;
  int eng_small;
  int loop_small;
  int eng_tiny;
  int loop_tiny;
} bench_t;

typedef struct benchset {
  char *name;
  bench_t *benchs;
} benchset_t;

#include "looptable__data.h"
const static int bs_count = sizeof(bs)/sizeof(bs[0]);

int main() {
  int i, j;
  printf("%% Do no edit - autogenerated from ${ciaotests}/sabsmach/looptable/do.sh\n");
  for (i = 0; i < bs_count; i++) {
    j = 0;
    printf("\\begin{table}[tbyp]");
    printf("\\centering\n");
    printf("\\small\n");
    printf("\\small\n");
    printf("\\begin{tabular}{||l||r|r|r|r|r||r|r||}\\hline\n");
    printf("\\multicolumn{8}{||c||}{\\textbf{Size comparison for %s instruction set}}\\\\\n", bs[i].name);
    printf("\\hline\n");
    printf("\\hline\n");
    printf("&\\multicolumn{5}{|c||}{\\textbf{loop}}&\\multicolumn{2}{|c||}{\\textbf{bytecode}}\\\\\n");
    printf("\\hline\n");
    printf("&nospec&spec/full&$\\sf\\Delta$\\%%&spec/stp&$\\sf\\Delta$\\%%&full&stripped\\\\\n");
    //    printf("\\textbf{Benchmark}&&full&&stripped&&&\\\\\n");
    printf("\\hline\n");
    printf("\\hline\n");
    int sum_delta_small = 0;
    int sum_delta_tiny = 0;
    while (1) {
      int delta_small;
      int delta_tiny;
      bench_t *b;
      b = &bs[i].benchs[j];
      if (b->name == 0) break;
      delta_small = 100-100*b->loop_small/b->loop_big;
      delta_tiny = 100-100*b->loop_tiny/b->loop_big;
      printf("\\textbf{%s} & %d & %d & %d\\%% & %d & %d\\%% & %d & %d \\\\\n",
	     b->name,
	     b->loop_big,
	     b->loop_small,
	     delta_small,
	     b->loop_tiny,
	     delta_tiny,
	     b->all_bytecode,
	     b->program_bytecode);
      printf("\\hline\n");
      sum_delta_small += delta_small;
      sum_delta_tiny += delta_tiny;
      j++;
    }
    printf("\\hline\n");
    printf("\\textbf{Average} &  &  & %d\\%% &  & %d\\%% &  &  \\\\\n",
	     sum_delta_small/j,
	     sum_delta_tiny/j);
    printf("\\hline\n");
    printf("\\end{tabular}\n");
    printf("\\caption{Sizes for instruction set %s}\n", bs[i].name);
    printf("\\label{tab:sizes-%s}\n", bs[i].name);
    printf("\\tablepost\n");
    printf("\\end{table}\n");
  }
  return 0;
}

