#!/bin/sh

# Number of processors we are going to use in the compilation process.
# In general, the number of processors available minus one, except if
# we have just one processor, of course.  If we do not know how to
# work out the number of processors, we'll use just one.

case $1 in
SYMM)        echo `/etc/online -N` 1 - p | dc ;;
IRIX*)       echo `/usr/sbin/mpadmin -n | tail -1` 1 - p | dc ;;
SunOS4*)     echo 1 ;;
Solaris*)    echo `/usr/bin/mpstat | /usr/bin/wc -l` 1 - p | dc ;;
Win32*)      echo 1 ;;
LINUX*)      if (test -e /proc/cpuinfo) && (test -e /bin/grep) ;
	     then echo `/bin/grep processor /proc/cpuinfo | wc --lines` ;
	     else if (test -e /proc/cpuinfo) && (test -e /usr/bin/grep) ;
	     then echo `/usr/bin/grep processor /proc/cpuinfo | wc --lines` ;
	     else echo 1; fi ; fi ;;
*)           echo 1 ;;
esac
