% TODO: I cannot call this one ciaopp.pl... why?
:- use_package(assertions).

:- comment(title,"The Ciao Prolog Preprocessor").
:- comment(author,"The CLIP Group").

:- comment(module,"
[Full documentation in the
 @uref{on-line HTML reference manual}{ciaopp-1.2.0.html/ciaopp.html}
and the
 @uref{on-line HTML internals reference manual}{ciaopp_internals-1.2.0.html/ciaopp_internals.html}]

CiaoPP is the precompiler of the Ciao Prolog development
environment. CiaoPP can perform a number of program debugging,
analysis, and source-to-source transformation tasks on (Ciao) Prolog
programs. These tasks include:

@begin{itemize}
@item Inference of properties of the predicates and literals of the
   program, including types, modes and other variable instantiation
   properties, non-failure, determinacy, bounds on computational cost,
   bounds on sizes of terms in the program, etc.

@item Certain kinds of static debugging, finding errors before
   running the program. This includes checking how programs call
   system library predicates and also checking the assertions present
   in the program or in other modules used by the program. Such
   assertions represent essentially partial specifications of the
   program.

@item Several kinds of source to source program transformations such
   as program specialization, partial evaluation of a program, program
   parallelization (taking granularity control into account),
   inclusion of run-time tests for assertions which cannot be checked
   completely at compile-time, etc.
@end{itemize}

The information generated by analysis, the assertions in the system
libraries, and the assertions optionally included in user programs as
specifications are all written in the same assertion language, which
is in turn also used by the Ciao system documentation generator,
@tt{lpdoc}.
").

% <UL><LI><A HREF=ciaopp_html/ciaopp.html><B>ciaopp</B> Reference Manual - in html hypertext format </A></UL><UL><LI><A HREF=ciaopp.pdf.gz><B>ciaopp</B> Reference Manual - in Adobe pdf (acrobat) format (compressed)</A></UL><UL><LI><A HREF=ciaopp.ps.gz><B>ciaopp</B> Reference Manual - in postscript format (compressed)</A></UL><A NAME="lpdoc"></A>

main.
