worker_t *free_wam(void);
bool_t program_usage(Argdecl);
bool_t internal_symbol_usage(Argdecl);
bool_t statistics(Argdecl);
bool_t total_usage(Argdecl);
tagged_t *checkalloc(int size);
tagged_t *checkrealloc(tagged_t *ptr, int decr, int size);
worker_t *create_wam_storage(void);
void checkdealloc(tagged_t *ptr, int decr);
void create_wam_areas(Argdecl);
void init_alloc(void);
extern ENG_INT total_mem_count;
extern ENG_INT num_of_predicates;
void release_wam(Argdecl);
